- hosts: localhost
  become: yes
  gather_facts: false
  vars:
    openshift_token: <<TOKEN>>
    openshift_url:  <<URL>>
    insecure_skip_tls_verify: true
    project_namespace: quarkus-cafe
    delete_deployment: false
    default_owner: <<OWNER>>
    default_group: <<GROUP>>
    version_barista: 2.5.0
    version_core: 2.5.0
    version_customermocker: 2.3.0
    version_kitchen: 2.5.0
    version_web: 2.5.0
    skip_amq_install: true
    amqstartingCSV: amqstreams.v1.5.3
    skip_quarkus_cafe_barista: true
    skip_quarkus_cafe_core: true
    skip_quarkus_cafe_kitchen: true
    skip_quarkus_cafe_web: skip
    skip_quarkus_cafe_customermock: skip
    quarkus_build_memory_limit: 6Gi
    quarkus_build_cpu_limit: 1
    quarkus_core_build_memory_limit: 6Gi
    domain: <<DOMAIN>>  # Change This value
  roles:
    - tosin2013.quarkus_cafe_demo_role
