- hosts: localhost
  become: yes
  gather_facts: false
  vars:
    openshift_token: tnV9L0COlG9MMMGfN43rSbiw9Y5jNccDKsg8RBx89pE
    openshift_url:  https://api.cluster-delta-5388.delta-5388.sandbox1073.opentlc.com:6443
    insecure_skip_tls_verify: true
    project_namespace: quarkus-cafe
    delete_deployment: false
    default_owner: jeremydavis
    default_group: staff
    version_barista: 2.2.6
    version_core: 2.2.3
    version_customermocker: 2.2
    version_kitchen: 2.2.3
    version_web: 2.2.5
    skip_amq_install: false
    amqstartingCSV: amqstreams.v1.5.3
    skip_quarkus_cafe_barista: false
    skip_quarkus_cafe_core: false
    skip_quarkus_cafe_kitchen: false
    skip_quarkus_cafe_web: false
    skip_quarkus_cafe_customermock: false
    quarkus_build_memory_limit: 6Gi
    quarkus_build_cpu_limit: 1
    quarkus_core_build_memory_limit: 6Gi
    domain: cluster-lou-8d2b.lou-8d2b.sandbox74.opentlc.com  # Change This value
  roles:
    - tosin2013.quarkus_cafe_demo_role